# Generated by Django 6.0.5 on 2026-07-12 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nome', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.BigIntegerField(default=1)),
                ('meta_horas', models.FloatField(default=0.0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_metas', to='home.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeDoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.BigIntegerField(default=1)),
                ('dia_semana', models.CharField(choices=[('Segunda', 'Segunda'), ('Terça', 'Terça'), ('Quarta', 'Quarta'), ('Quinta', 'Quinta'), ('Sexta', 'Sexta'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20)),
                ('horas_feitas', models.FloatField(default=0.0)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_dias', to='home.atividade')),
            ],
            options={
                'unique_together': {('dia_semana', 'atividade')},
            },
        ),
    ]
