# Generated by Django 5.1.3 on 2026-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_atividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
    ]
